### ISSUE TITLE
Files Management method putFile can't be folder specific it can only be root folder or /

### ISSUE THREAD

**Issue by Arisdolanan** [noveens/js-owncloud-client-browser#1]

**Comment by hanifkf12** [comment]
you must provide your target file name at putFiles like this:
`oc.files.putFile('/mkdirfolder/aku2.pdf', `${path.join(__dirname, "../public/test.pdf")}`).then(status => {
    console.log(status);
  }).catch(error => {
    console.log(error);
  });`
